phases:
  build:
    commands:
       - "echo Build started on `date`"
       - "echo Building the Docker image..."
       - "cd ci-cd-python "
       - "docker build -t python-demo . "
       - "docker tag python-demo:latest 372045710271.dkr.ecr.us-east-1.amazonaws.com/python-demo"
  post_build:
    commands:
       - "echo Build completed on `date`"
       - "echo Pushing the Docker image..."
       - "docker push 372045710271.dkr.ecr.us-east-1.amazonaws.com/python-demo"
  pre_build:
    commands:
       - "echo Logging in to Amazon ECR..."
       - "$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)"
version: 0.2
